version: '3.1'

services:
  application:
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - data:/data
    networks:
      - application-network

volumes:
  data: {}
networks:
  application-network:
    driver: bridge
