name: Deploy website
on:
  push:
    branches: [ master ]
    paths: [ website/** ]

jobs:
  deploy:
    name: Deploy Production Site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Minify Files
      uses: anthonyftwang/minify-action@v1.0.1
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        PROJECT_PATH: ./website
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

