name: Deploy website
on:
  push:
    branches: [ master ]
    paths: [ website/** ]

jobs:
  deploy:
    name: Deploy Production Site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Dependencies
      working-directory: ./website
      run: npm ci
    - name: Build Site
      working-directory: ./website
      run: npm run build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        PROJECT_PATH: ./website
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

